### ISSUE TITLE
[ 📝 Devlog ] 이유진 / 2022-09-29

### ISSUE THREAD

**Issue by nuuco** [codestates-seb/seb39_main_015#142]
### - 오늘은 어떤 작업을 진행했나요?
- 빌딩 높이를 고정시켜서 층수에 따라 유닛 크기가 달라지게 만들기
- 상대 길이를 사용해서 반응형(모바일 등)도 대응 가능하게 구성

https://user-images.githubusercontent.com/89282099/192988926-653d101a-e5f6-4718-8eee-a8d625ed52ac.mp4

### - 오늘 작업 내용중 어려웠던 부분이 있었나요?
- 층 별로 예외처리를 하지 않고 styed-components의 props로 층 높이를 내려줘서 변수로 활용하는 방식을 떠올리기가 힘들었습니다.
- 평소에 사용해볼 기회가 없었던 CSS 변수와 함수를 적극적으로 써볼 수 있었습니다 :-) 
- clac(), min(), var() 를 활용해 유지보수하기 편하고 원하는 사이즈로 출력되는 변수를 설정하는 게 오래 걸렸습니다.
- 👉 item-height 를 수정하면 전체 변수값이 조정되도록 만들었습니다. 유닛의 너비도 item-height 에 따라 설정됩니다.
- CSS(styled-components) 코드
  ```css
    --total-floor: ${(props) => (props.totalFloor <= 2 ? 2 : props.totalFloor)};
    --item-height: min(90vw / 3 * (2 / 3), 90vh / (var(--total-floor) + 0.8));
    --item-width: calc(var(--item-height) * (3 / 2));
    --rooftop-height: calc(var(--item-height) * (3 / 5));
    --container-width: calc(var(--item-width) * 3 + 10px);
  
    /** 유닛이 1개, 2개 일 때 사이즈 분기 처리 */
    --one-item-height: min(var(--item-height) * 2, 80vh * (5 / 8));
    --one-item-width: calc(var(--one-item-height) * (3 / 2));
    --two-item-height: min(var(--item-height) * (3 / 2), 80vh * (5 / 8));
    --two-item-width: calc(var(--two-item-height) * (3 / 2));
    --one-rooftop-height: calc(var(--one-item-height) * (3 / 5));
    --two-rooftop-height: calc(var(--two-item-height) * (3 / 5));
  ```

### - 내일은 어떤 작업을 계획하고 있나요?
- [ ] 고양이, 배경 이미지 정제에서 images 폴더에 넣기 (스프라이트 기법 활용)
- [ ] 유닛 별 배경 넣고, 구역 나눠서 루빗 배치해보기 (배경 별로 배치 다르게 줄 것)
